#!/usr/bin/env bash

# Install Nginx
package { 'nginx':
  ensure => 'installed',
}

# Configure custom 404 page
file { '/var/www/html/error_404.html':
  ensure  => 'present',
  content => "Ceci n'est pas une page\n",
}

file { '/etc/nginx/sites-available/default':
  ensure  => 'present',
  content => template('nginx/default.erb'),
  require => File['/var/www/html/error_404.html'],
}

# Restart Nginx service
service { 'nginx':
  ensure    => 'running',
  enable    => true,
  subscribe => File['/etc/nginx/sites-available/default'],
}
