#!/usr/bin/env bash

#Install Nginx
sudo apt-get update -y -qq && sudo apt-get install nginx -y

# Configure Nginx to have a custom 404 page
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}
EOF'

# Create the custom 404 page
sudo bash -c 'echo "Ceci n'est pas une page" > /var/www/html/404.html'

# Restart Nginx
sudo service nginx restart

echo "Configuration completed."
