#!/bin/bash

#set the custom HTTP header
custom_header="add_header X-Served-By \$hostname;"

# Update Nginx configuration to add the custom header
sudo sed -i "/^http {/a $custom_header" /etc/nginx/nginx.conf

# Restart Nginx to apply changes
sudo systemctl restart nginx
