#!/usr/bin/env bash
#This script configures Nginx to add a custom HTTP response header

# Update package index
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Configure custom HTTP response header
sudo sed -i '/server_name _;/a \\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
