#!/usr/bin/env bash
# This script gives information about the school file

file_path="school"

if [ -e "$file_path" ]; then
    echo "$file_path file exists"
    
    if [ -s "$file_path" ]; then
        echo "$file_path file is not empty"
    else
        echo "$file_path file is empty"
    fi

    if [ -f "$file_path" ]; then
        echo "$file_path is a regular file"
    else
        # If the file is not a regular file, print nothing
        :
    fi
else
    echo "$file_path file does not exist"
fi
