#!/usr/bin/env bash

# Fixes server bug
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
pkill apache2  # Kills any running Apache processes
# restart
su nginx -s /bin/bash -c 'service nginx restart'  # Restarts Nginx as the nginx user
